package com.jetbrains.util.filetype

enum class ProcessorArchitecture(v: Int) {
  /**
  * x86
  */
  PROCESSOR_ARCHITECTURE_INTEL(0),
  PROCESSOR_ARCHITECTURE_MIPS(1),
  PROCESSOR_ARCHITECTURE_ALPHA(2),
  PROCESSOR_ARCHITECTURE_PPC(3),
  PROCESSOR_ARCHITECTURE_SHX(4),

  /**
  * armv7*
  */
  PROCESSOR_ARCHITECTURE_ARM(5),

  /**
  * Intel Itanium-based
  */
  PROCESSOR_ARCHITECTURE_IA64(6),
  PROCESSOR_ARCHITECTURE_ALPHA64(7),
  PROCESSOR_ARCHITECTURE_MSIL(8),

  /**
  * x86_64, amd64, x64
  */
  PROCESSOR_ARCHITECTURE_AMD64(9),
  PROCESSOR_ARCHITECTURE_IA32_ON_WIN64(10),
  PROCESSOR_ARCHITECTURE_NEUTRAL(11),

  /**
  * arm64v8, aarch64
  */
  PROCESSOR_ARCHITECTURE_ARM64(12),

  /**
  * Unknown architecture.
  */
  PROCESSOR_ARCHITECTURE_UNKNOWN(0xFFFF)
}

