namespace JetBrains.FormatRipper.Dmg;

public enum CSMAGIC_CONSTS : uint
{
  CODEDIRECTORY = 0,
  INFOSLOT = 1,
  REQUIREMENTS = 2,
  RESOURCEDIR = 3,
  APPLICATION = 4,
  ENTITLEMENTS = 5,
  ENTITLEMENTS_DER = 7,
  ALTERNATE_CODEDIRECTORIES = 0x1000,
  CMS_SIGNATURE = 0x10000,
  UNKNOWN
}