keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "actalisauthenticationrootca [jdk]" -file actalisauthenticationrootca.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "addtrustexternalca [jdk]" -file addtrustexternalca.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "addtrustqualifiedca [jdk]" -file addtrustqualifiedca.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "affirmtrustcommercialca [jdk]" -file affirmtrustcommercialca.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "affirmtrustnetworkingca [jdk]" -file affirmtrustnetworkingca.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "affirmtrustpremiumca [jdk]" -file affirmtrustpremiumca.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "affirmtrustpremiumeccca [jdk]" -file affirmtrustpremiumeccca.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "amazonrootca1 [jdk]" -file amazonrootca1.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "amazonrootca2 [jdk]" -file amazonrootca2.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "amazonrootca3 [jdk]" -file amazonrootca3.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "amazonrootca4 [jdk]" -file amazonrootca4.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "baltimorecybertrustca [jdk]" -file baltimorecybertrustca.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "buypassclass2ca [jdk]" -file buypassclass2ca.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "buypassclass3ca [jdk]" -file buypassclass3ca.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "camerfirmachambersca [jdk]" -file camerfirmachambersca.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "camerfirmachamberscommerceca [jdk]" -file camerfirmachamberscommerceca.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "camerfirmachambersignca [jdk]" -file camerfirmachambersignca.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "certignaca [jdk]" -file certignaca.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "certumca [jdk]" -file certumca.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "certumtrustednetworkca [jdk]" -file certumtrustednetworkca.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "chunghwaepkirootca [jdk]" -file chunghwaepkirootca.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "comodoaaaca [jdk]" -file comodoaaaca.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "comodoeccca [jdk]" -file comodoeccca.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "comodorsaca [jdk]" -file comodorsaca.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "digicertassuredidg2 [jdk]" -file digicertassuredidg2.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "digicertassuredidg3 [jdk]" -file digicertassuredidg3.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "digicertassuredidrootca [jdk]" -file digicertassuredidrootca.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "digicertglobalrootca [jdk]" -file digicertglobalrootca.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "digicertglobalrootg2 [jdk]" -file digicertglobalrootg2.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "digicertglobalrootg3 [jdk]" -file digicertglobalrootg3.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "digicerthighassuranceevrootca [jdk]" -file digicerthighassuranceevrootca.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "digicerttrustedrootg4 [jdk]" -file digicerttrustedrootg4.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "dtrustclass3ca2 [jdk]" -file dtrustclass3ca2.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "dtrustclass3ca2ev [jdk]" -file dtrustclass3ca2ev.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "entrust2048ca [jdk]" -file entrust2048ca.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "entrustevca [jdk]" -file entrustevca.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "entrustrootcaec1 [jdk]" -file entrustrootcaec1.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "entrustrootcag2 [jdk]" -file entrustrootcag2.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "entrustrootcag4 [jdk]" -file entrustrootcag4.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "geotrustglobalca [jdk]" -file geotrustglobalca.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "geotrustprimaryca [jdk]" -file geotrustprimaryca.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "geotrustprimarycag2 [jdk]" -file geotrustprimarycag2.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "geotrustprimarycag3 [jdk]" -file geotrustprimarycag3.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "geotrustuniversalca [jdk]" -file geotrustuniversalca.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "globalsignca [jdk]" -file globalsignca.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "globalsigneccrootcar4 [jdk]" -file globalsigneccrootcar4.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "globalsigneccrootcar5 [jdk]" -file globalsigneccrootcar5.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "globalsignr3ca [jdk]" -file globalsignr3ca.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "globalsignrootcar6 [jdk]" -file globalsignrootcar6.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "godaddyclass2ca [jdk]" -file godaddyclass2ca.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "godaddyrootg2ca [jdk]" -file godaddyrootg2ca.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "haricaeccrootca2015 [jdk]" -file haricaeccrootca2015.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "haricarootca2015 [jdk]" -file haricarootca2015.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "identrustcommercial [jdk]" -file identrustcommercial.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "identrustpublicca [jdk]" -file identrustpublicca.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "letsencryptisrgx1 [jdk]" -file letsencryptisrgx1.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "luxtrustglobalroot2ca [jdk]" -file luxtrustglobalroot2ca.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "luxtrustglobalrootca [jdk]" -file luxtrustglobalrootca.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "quovadisrootca [jdk]" -file quovadisrootca.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "quovadisrootca1g3 [jdk]" -file quovadisrootca1g3.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "quovadisrootca2 [jdk]" -file quovadisrootca2.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "quovadisrootca2g3 [jdk]" -file quovadisrootca2g3.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "quovadisrootca3 [jdk]" -file quovadisrootca3.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "quovadisrootca3g3 [jdk]" -file quovadisrootca3g3.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "secomscrootca1 [jdk]" -file secomscrootca1.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "secomscrootca2 [jdk]" -file secomscrootca2.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "securetrustca [jdk]" -file securetrustca.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "sslrooteccca [jdk]" -file sslrooteccca.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "sslrootevrsaca [jdk]" -file sslrootevrsaca.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "sslrootrsaca [jdk]" -file sslrootrsaca.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "starfieldclass2ca [jdk]" -file starfieldclass2ca.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "starfieldrootg2ca [jdk]" -file starfieldrootg2ca.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "starfieldservicesrootg2ca [jdk]" -file starfieldservicesrootg2ca.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "swisssigngoldg2ca [jdk]" -file swisssigngoldg2ca.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "swisssignplatinumg2ca [jdk]" -file swisssignplatinumg2ca.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "swisssignsilverg2ca [jdk]" -file swisssignsilverg2ca.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "teliasonerarootcav1 [jdk]" -file teliasonerarootcav1.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "thawteprimaryrootca [jdk]" -file thawteprimaryrootca.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "thawteprimaryrootcag2 [jdk]" -file thawteprimaryrootcag2.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "thawteprimaryrootcag3 [jdk]" -file thawteprimaryrootcag3.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "ttelesecglobalrootclass2ca [jdk]" -file ttelesecglobalrootclass2ca.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "ttelesecglobalrootclass3ca [jdk]" -file ttelesecglobalrootclass3ca.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "usertrusteccca [jdk]" -file usertrusteccca.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "usertrustrsaca [jdk]" -file usertrustrsaca.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "utnuserfirstobjectca [jdk]" -file utnuserfirstobjectca.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "verisignclass3g3ca [jdk]" -file verisignclass3g3ca.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "verisignclass3g4ca [jdk]" -file verisignclass3g4ca.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "verisignclass3g5ca [jdk]" -file verisignclass3g5ca.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "verisignuniversalrootca [jdk]" -file verisignuniversalrootca.cer -storepass changeit
keytool -import -keystore /opt/jdk-17/lib/security/cacerts -alias "xrampglobalca [jdk]" -file xrampglobalca.cer -storepass changeit
